const { PERMISSIONS } = require("./permissions");

const ROLES = Object.freeze({
  ADMIN: "admin",
  ICT_OFFICER: "ict_officer",
  TECHNICIAN: "technician",
  STAFF: "staff",
});

const USER_TYPES = Object.freeze({
  EMPLOYEE: "employee",
  INTERN: "intern",
  CORPER: "corper",
  CONTRACTOR: "contractor",
  GUEST: "guest",
});

const TEMPORARY_USER_TYPES = Object.freeze([
  USER_TYPES.INTERN,
  USER_TYPES.CORPER,
  USER_TYPES.CONTRACTOR,
  USER_TYPES.GUEST,
]);

const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.ADMIN]: Object.freeze([
    PERMISSIONS.TICKETS_CREATE,
    PERMISSIONS.TICKETS_VIEW_OWN,
    PERMISSIONS.TICKETS_VIEW_DEPARTMENT,
    PERMISSIONS.TICKETS_VIEW_ALL,
    PERMISSIONS.TICKETS_ASSIGN,
    PERMISSIONS.TICKETS_UPDATE_STATUS,
    PERMISSIONS.TICKETS_CLOSE,
    PERMISSIONS.TICKETS_REOPEN,
    PERMISSIONS.ASSETS_CREATE,
    PERMISSIONS.ASSETS_EDIT,
    PERMISSIONS.ASSETS_ASSIGN,
    PERMISSIONS.ASSETS_DELETE,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_EDIT,
    PERMISSIONS.USERS_DEACTIVATE,
    PERMISSIONS.USERS_CHANGE_ROLE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.AUDIT_LOGS_VIEW,
  ]),
  [ROLES.ICT_OFFICER]: Object.freeze([
    PERMISSIONS.TICKETS_CREATE,
    PERMISSIONS.TICKETS_VIEW_OWN,
    PERMISSIONS.TICKETS_VIEW_DEPARTMENT,
    PERMISSIONS.TICKETS_VIEW_ALL,
    PERMISSIONS.TICKETS_ASSIGN,
    PERMISSIONS.TICKETS_UPDATE_STATUS,
    PERMISSIONS.TICKETS_CLOSE,
    PERMISSIONS.TICKETS_REOPEN,
    PERMISSIONS.ASSETS_CREATE,
    PERMISSIONS.ASSETS_EDIT,
    PERMISSIONS.ASSETS_ASSIGN,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.AUDIT_LOGS_VIEW,
  ]),
  [ROLES.TECHNICIAN]: Object.freeze([
    PERMISSIONS.TICKETS_CREATE,
    PERMISSIONS.TICKETS_VIEW_OWN,
    PERMISSIONS.TICKETS_UPDATE_STATUS,
    PERMISSIONS.TICKETS_CLOSE,
    PERMISSIONS.TICKETS_REOPEN,
    PERMISSIONS.ASSETS_EDIT,
  ]),
  [ROLES.STAFF]: Object.freeze([
    PERMISSIONS.TICKETS_CREATE,
    PERMISSIONS.TICKETS_VIEW_OWN,
    PERMISSIONS.TICKETS_CLOSE,
    PERMISSIONS.TICKETS_REOPEN,
  ]),
});

module.exports = {
  ROLE_PERMISSIONS,
  ROLES,
  TEMPORARY_USER_TYPES,
  USER_TYPES,
};
