import {
  LuBell,
  LuBookOpen,
  LuBuilding2,
  LuCalendarPlus,
  LuChartBar,
  LuCheck,
  LuChevronLeft,
  LuChevronRight,
  LuCircle,
  LuCircleCheckBig,
  LuClock3,
  LuDownload,
  LuExternalLink,
  LuEye,
  LuEyeOff,
  LuFileText,
  LuFilter,
  LuInfo,
  LuLayoutDashboard,
  LuLockKeyhole,
  LuLogOut,
  LuMenu,
  LuMonitor,
  LuPause,
  LuPackageOpen,
  LuPencil,
  LuPlay,
  LuPlus,
  LuRefreshCw,
  LuSearch,
  LuShieldCheck,
  LuTicket,
  LuTriangleAlert,
  LuTrash2,
  LuUndo2,
  LuUserCheck,
  LuUserPlus,
  LuUserRound,
  LuUserX,
  LuUsers,
  LuWrench,
  LuX,
} from 'react-icons/lu';

const ICONS = {
  asset: LuMonitor,
  bell: LuBell,
  book: LuBookOpen,
  building: LuBuilding2,
  calendar: LuCalendarPlus,
  chart: LuChartBar,
  check: LuCheck,
  complete: LuCircleCheckBig,
  clock: LuClock3,
  close: LuX,
  dashboard: LuLayoutDashboard,
  delete: LuTrash2,
  download: LuDownload,
  edit: LuPencil,
  filter: LuFilter,
  file: LuFileText,
  grid: LuLayoutDashboard,
  info: LuInfo,
  menu: LuMenu,
  next: LuChevronRight,
  open: LuExternalLink,
  pause: LuPause,
  play: LuPlay,
  plus: LuPlus,
  previous: LuChevronLeft,
  refresh: LuRefreshCw,
  search: LuSearch,
  shield: LuShieldCheck,
  ticket: LuTicket,
  user: LuUserRound,
  'user-add': LuUserPlus,
  'user-check': LuUserCheck,
  'user-remove': LuUserX,
  users: LuUsers,
  view: LuEye,
  'view-off': LuEyeOff,
  wrench: LuWrench,
  x: LuX,
  dot: LuCircle,
  logout: LuLogOut,
  lock: LuLockKeyhole,
  package: LuPackageOpen,
  alert: LuTriangleAlert,
  return: LuUndo2,
};

export function AppIcon({ name, size = 18, className = '', ...props }) {
  const Icon = ICONS[name] || LuCircle;
  return (
    <Icon
      className={`app-icon ${className}`.trim()}
      size={size}
      focusable="false"
      aria-hidden="true"
      {...props}
    />
  );
}

